### ISSUE TITLE
Setting file path

### ISSUE THREAD

**Issue by MohamadHalwani** [pwwiur/hough-counter#1]
I'm concerned of the proper way to add the image path ! I'm selecting the directory at first but the an error appears.
`python3 main.py 
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.8/tkinter/__init__.py", line 1892, in __call__
    return self.func(*args)
  File "main.py", line 135, in scales_onchange
    load_image()
  File "main.py", line 102, in load_image
    file_path = data_path + "/" + files[file_index]
IndexError: list index out of range
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.8/tkinter/__init__.py", line 1892, in __call__
    return self.func(*args)
  File "main.py", line 135, in scales_onchange
    load_image()
  File "main.py", line 102, in load_image
    file_path = data_path + "/" + files[file_index]
IndexError: list index out of range
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.8/tkinter/__init__.py", line 1892, in __call__
    return self.func(*args)
  File "main.py", line 135, in scales_onchange
    load_image()
  File "main.py", line 102, in load_image
    file_path = data_path + "/" + files[file_index]
IndexError: list index out of range
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.8/tkinter/__init__.py", line 1892, in __call__
    return self.func(*args)
  File "main.py", line 135, in scales_onchange
    load_image()
  File "main.py", line 102, in load_image
    file_path = data_path + "/" + files[file_index]
IndexError: list index out of range
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.8/tkinter/__init__.py", line 1892, in __call__
    return self.func(*args)
  File "main.py", line 135, in scales_onchange
    load_image()
  File "main.py", line 102, in load_image
    file_path = data_path + "/" + files[file_index]
IndexError: list index out of range
Loading:  /home/mhalwani/ProjectiveTransformation/image.png
Traceback (most recent call last):
  File "main.py", line 306, in <module>
    load_image()
  File "main.py", line 124, in load_image
    raise e
  File "main.py", line 118, in load_image
    show_info(title + " Circles found: " + (0 if circles is None else str(len(circles[0, :]))))
TypeError: can only concatenate str (not "int") to str
`

**Comment by titan2420** [comment]
I made a change in main.py file, Check if its fixed!
This bug occures when selecting an empty folder!

**Comment by MohamadHalwani** [comment]
![image](https://user-images.githubusercontent.com/60169316/155067147-af93d5cd-3d0d-4060-8342-a888ff655c46.png)

The code is working now, but for some reason I'm not able to detect a single circle ! I attached my image, I want to detect the 8 blue circles in the 4 corners.
Not sure if its a bug 
Also, when the code displays the image, it looks like its dimensions are changed !

**Comment by titan2420** [comment]
Dear Mohamad. You should configure parameters of Hough algorithm in top of window to be able to detect circles.
